services:
  env:
    image: go-exercism-env
    container_name: go-exercism-env
    hostname: arch-box

    network_mode: bridge
    userns_mode: keep-id

    stdin_open: true
    tty: true

    volumes:
      - ${PROJECT_PATH:-./src}:/home/developer/project:Z

      - ./cache:/home/developer/.cache

      - ./confs/.bashrc:/home/developer/.bashrc:Z
      - ./confs/helix:/home/developer/.config/helix:Z
      - ./confs/zellij:/home/developer/.config/zellij:Z
      - ./confs/exercism:/home/developer/.config/exercism:Z
